package com.example.ecobeauty.main;

import android.graphics.Color;

public class Constants {
    public static String[] IMAGENET_CLASSES = new String[]{"normal","fat","dry","combined"};
    public static final int IMG_SIZE = 224;
    public static String TAG_MAIN = "MainActivityLog";
    public static String TAG_ABOUT_APP = "AboutAppActivityLog";
    public static String IOE_ERROR_UPDATE = "UnableToUpdateDatabase";
    public static String IOE_ERROR_COPING = "ErrorCopyingDataBase";
    public static String[] COMPOSITION = new String[]{"name", "action", "danger", "describe_danger"};
    public static String DB_NAME_ONE = "comp11.db";
    public static String DB_PATH_ONE = "C:\\Users\\Aisov\\AndroidStudioProjects\\Project\\app\\src\\main\\assets";
    public static final int DB_VERSION = 1;
    public static String DB_NAME_THREE = "uhod1.db";
    public static String DB_PATH_THREE = "C:\\Users\\I.Am.Biersack\\Desktop\\proektAmina\\ecobeauty\\app\\src\\main\\assets";
    public static String DATABASES = "/databases/";
    public static String DATA_DATA = "/data/data/";
    public static final int DATABASE_VERSION = 1;
    public static final String DATABASE_NAME = "easyPronounce";
    public static final String TABLE_WORD = "words";
    public static final String KEY_ID = "id";
    public static final String KEY_WORD = "word";
    public static final String KEY_POS = "partofspeech";
    public static final String NEW_API = "NewApi";
    public static final String FILLED = "filled";
    public static final String EMPTY = "empty";
    public static final String NETWORK_FILE= "model_densenet121.pt";
    public static final String DATA = "data";
    public static final String PRED = "pred";
    public static final String CHECK_TYPE = "checkType";
    public static final String NORMAL = "normal";
    public static final String FAT = "fat";
    public static final String DRY = "dry";
    public static final String COMBINED = "combined";
    public static final String PYTORCH = "pytorchandroid";
    public static final String ERROR_PROCESS_ONE = "Error process asset 1 ";
    public static final String ERROR_PROCESS_TWO = "Error process asset 2 ";
    public static final String FILE_PATH =" to file path";
    public static final String SAVED_TEXT = "saved_text";
    public static final String SP_WORDS = "spWords";
    public static final String MORNING = "Утро";
    public static final String EVENING = "Вечер";
    public static final String WORD = "word";
    public static final String POS = "pos";
    public static final String NORMAL_TYPE = "Нормальный тип";
    public static final String FAT_TYPE = "Жирный тип";
    public static final String DRY_TYPE = "Сухой тип";
    public static final String COMBINED_TYPE = "Комбинированный тип";
    public static final String BASIC_NAME_USER_PRODUCT = "UserProduct";
    public static final String BASIC_NAME_USER_WISH = "UserWish";
    public static final String SAVED_DATE_CHECKALL = "saved_date_checkall" ;
    public static final String SAVED_DATE = "saved_date";
    public static final String MOTIV_COUNT = "saved_motivation_count";
    public static final String SIMPLE_DATE_FORMAT="MMM dd yyyy";
    public static final String NULL ="null";
    public static final String LINE_ONE =  "line1";
    public static final String LINE_TWO =  "line2";
    public static final String NAME = "name";
    public static final String USER_COSMETICS = "UserCosmetics";
    public static final int DEFAULT_TEXT_COLOR = Color.TRANSPARENT;
    public static final String LAYOUT_WIDTH = "layout_width";
    public static final String LAYOUT_HEIGHT = "layout_height";
}

